runtime: nodejs16
env: standard
handlers:
  - url: /preview(\/|)
    static_files: dist/index.html
    upload: dist/index.html
  - url: /preview(\/event-detail|\/event-list)(.*)
    static_files: dist/index.html
    upload: dist/index.html
  - url: /preview/(.*)
    static_files: dist/\1
    upload: dist/(.*)